=begin
Preston Copeland
August 24, 2015
Project Euler

Problem 44: Pentagonal Numbers

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

Answer: 5482660 (solved myself)
=end

def pentagonal_number(number)
  (number*(3*number-1))/2
end

def pentagonal_number?(number)
  n = (1.0/6) + Math.sqrt( (24*number + 1.0)/36.0 )
  n.ceil - n <= 0.00001
end

def pentagonal_numbers
  min_diff = 1000000000
  (1..5000).each do |j|
    (1..5000).each do |k|
      pj = pentagonal_number(j)
      pk = pentagonal_number(k)
      sum = pk + pj
      diff = (pk - pj).abs
      if(pentagonal_number?(sum) && pentagonal_number?(diff))
        if(diff < min_diff)
          min_diff = diff
        end
      end
    end
  end
  min_diff
end

