=begin
Preston Copeland
September 15, 2015
Project Euler

Problem 45: Triangular, Pentagonal, Hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle      Tn=n(n+1)/2       1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2      1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

Answer: 1533776805 (solved myself) Became 44854th person to do so.
=end
def integer? number
  epsilon = 1e-6
  (number - number.ceil).abs < epsilon
end

def pentagonal? number
  n = (1 + Math.sqrt(1 + 24*number)).to_f/6
  integer? n
end

def hexagonal? number
  h = (1 + Math.sqrt(1 + 8*number)).to_f/4
  integer? h
end

def next_triple_threat
  n = 286
  while true
    t = (n*(n+1))/2
    return t if(pentagonal?(t) && hexagonal?(t))
    n += 1
  end
end